project:
  type: website
  output-dir: docs
  
website:
  title: "Weisi's website"
  description: "The personal website of Weisi Chen"
  site-url: https://www.weisichen.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blog.qmd
    tools:
      - icon: twitter
        href: https://x.com/ChenSophie16
      - icon: github
        href: https://github.com/WeisiChen1995/Weisi_website
      - icon: linkedin
        href: https://www.linkedin.com/in/weisi-chen-000334239/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Weisi Chen"

format:
  html:
    theme: Sandstone
    toc: true

editor: source

