project:
  type: website
  #output-dir: docs
  render: 
    - "index.qmd"
    - "about.qmd"
    - "cv.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"
    - "climate.qmd"
    - "sst.qmd"
  
website:
  title: "Weisi Chen"
  favicon: img/logo2.jpg
  site-url: https://weisichen.org
  navbar:
    logo: img/logo2.jpg
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - text: "About"
            href: about.qmd
          - text: "Curriculum Vitae"
            href: cv.qmd
      - text: "Projects"
        menu:
           - text: "NSW Rainfall"
             href: climate.qmd
           - text: "AU Sea Surface Temperature"
             href: sst.qmd
    right:
      - text: "🤍"
        href: blog/index.qmd
        aria-label: "Other"
    tools:
      - icon: github
        href: https://github.com/WeisiChen1995/Weisi_website
        
  page-footer:
    center:
      - text: "<a href='https://github.com/WeisiChen1995' target='blank'><i class='bi bi-github'></i></a> &nbsp;<a href='https://www.linkedin.com/in/weisi-chen-000334239/' target='blank'><i class='bi bi-linkedin'></i></a> &nbsp;<a href='https://scholar.google.com.au/citations?user=iCapTGoAAAAJ&hl=en/' target='blank'><i class='ai ai-google-scholar fa-lg'></i></a> &nbsp;<a href='https://www.researchgate.net/profile/Weisi-Chen-3' target='blank'><i class='ai ai-researchgate fa-lg'></i></a> &nbsp;<a <br>Website made with 🖤 and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a><br>© 2025 Weisi Chen"
    left: | 
      <script data-goatcounter="https://weisichen.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>

format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"

editor: source

