project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "about.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"
  
website:
  title: "Tangpai's website"
  description: "The personal website of Tangpai"
  site-url: https://www.weisichen.com
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "My blog"
        href: blog/index.qmd
    tools:
      - icon: github
        href: https://github.com/WeisiChen1995/Weisi_website
        
  page-footer:
    center:
      - text: "<a <br>Website made using <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a><br>© 2025 Tangpai"

format:
  html:
    theme: Sandstone
    toc: true
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"

editor: source

