project:
  type: website
  output-dir: docs
  render: 
    - "index.qmd"
    - "about.qmd"
    - "research.qmd"
    - "projects.qmd"
    - "blog/index.qmd"
  
website:
  title: "Weisi's website"
  description: "The personal website of Weisi Chen"
  site-url: https://www.weisichen.com
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Project"
        href: projects.qmd
      - text: "My blog"
        href: blog/index.qmd
    tools:
      - icon: twitter
        href: https://x.com/ChenSophie16
      - icon: github
        href: https://github.com/WeisiChen1995/Weisi_website
      - icon: linkedin
        href: https://www.linkedin.com/in/weisi-chen-000334239/
  page-footer:
    center:
      - text: "<a href='https://github.com/WeisiChen1995/Weisi_CV/blob/main/cv-wc.pdf'>CV</a> &nbsp;<a href='https://github.com/WeisiChen1995' target='blank'><i class='bi bi-github'></i></a> &nbsp;<a href='https://www.linkedin.com/in/weisi-chen-000334239/' target='blank'><i class='bi bi-linkedin'></i></a> &nbsp;<a href='https://scholar.google.com.au/citations?user=iCapTGoAAAAJ&hl=en/' target='blank'><i class='ai ai-google-scholar fa-lg'></i></a> &nbsp;<a href='https://www.researchgate.net/profile/Weisi-Chen-3' target='blank'><i class='ai ai-researchgate fa-lg'></i></a> &nbsp;<a <br>Site made with <i class='bi bi-heart-fill'></i>,  &nbsp;<a href='https://github.com/WeisiChen1995' target='blank'><i class='bi bi-github'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a><br>© 2025 Weisi Chen"

format:
  html:
    theme: Sandstone
    toc: true
    # This is to include fontawesome and academic icons in the headers:
    include-in-header: "_includes/header.html"

editor: source

