---
title: "Curriculum Vitae"
date: "2025-10-10"
page-layout: full
toc: true
---

[📄 See full CV here](https://github.com/WeisiChen1995/CV/blob/main/cv-wc.pdf?raw=TRUE) 

# Contact

[✉️ weisi.0816@gmail.com](mailto:weisi.0816@gmail.com)

# Brief Biography

I am a data analyst with a former background in pharmacy, bringing a unique combination of
domain knowledge and analytical expertise to complex health data projects. I am highly disciplined, detail-oriented, and driven by a strong passion for
reproducible research, statistical analysis, and data visualization.

I am proficient in statistical software such as R and SAS, with experience in data cleaning, analysis, visualization, and statistical modelling.
Over the years, I have worked with large, linked health administrative datasets across platforms such as SURE, PLIDA, and NHDH.
I am familiar with nationwide datasets, including hospital admissions, emergency department records, Pharmaceutical Benefits Scheme (PBS)
and Medicare Benefits Schedule (MBS) claims, and death registrations.

I am deeply committed to continuous learning and professional development,
always eager to explore new packages, techniques, or skills that enhance my ability
to analyze data effectively and deliver meaningful insights.


# Professional Interests 

• Reproducible Research • Data Visualization • Statistical modeling


# Education Background

- 2021 – 2023, **Master of Health Data Science**, University of New South Wales  
- 2015 – 2019, **Bachelor of Pharmacy**, University of Sydney

# Publications

[Google Scholar Profile](https://scholar.google.com.au/citations?user=iCapTGoAAAAJ&hl=en)


# Professional Experience

I transitioned into data-focused work in 2021 through the Master of Health Data Science program at the University of New South Wales (UNSW). My first quantitative project was my master’s dissertation at the Kirby Institute, UNSW, where I developed a beta-distributed generalized linear mixed-effects model (GLMM) to examine changes in cardiovascular risk among people living with HIV. 

Since July 2023, I have been working as a Data Scientist at the School of Public Health, UNSW, and the School of Pharmacy, University of Sydney (USYD). In this role, I have gained extensive experience working with large, linked administrative health datasets through platforms such as SURE, PLIDA, and NHDH. My responsibilities include building population-based cohorts across multiple data sources and conducting project-specific statistical analyses to support research in public health and pharmacoepidemiology.



