---
title: "Projects"
categories:
  - Masters Dissertation
format: 
  html:
    toc: true
    toc-depth: 4  
---

#### **Masters Dissertation : Changes in Atherosclerotic Cardiovascular Disease (ASCVD) Risk Over Time in People Living with HIV**
This dissertation aims to investigate changes in the five-year ASCVD risk over time among people living with HIV. The five-year ASCVD risk was calculated using the D:A:D equation, a well-established tool in cardiovascular research for individuals with HIV.

To analyze these data, beta-distributed generalized linear mixed models (GLMMs) were employed. Beta regression is commonly used for modeling continuous data that are expressed as percentages or proportions, such as ASCVD risk scores, which are constrained between 0 and 1 and are often highly skewed. GLMMs extend beta regression by incorporating random effects, making them well-suited for longitudinal data where measurements from the same individual are correlated over time.

The preferred model, based on the best goodness-of-fit statistics, was a piecewise linear model with a breakpoint at 3 years. This model included both the intercept and the time slope as random effects. The breakpoint was determined by evaluating follow-up time points every six months, with the model featuring a 3-year breakpoint yielding the lowest Akaike Information Criterion (AIC) value.

[Download the PowerPoint Presentation](dissertation_presentation.pptx)